print("** Message form LUA: Script testscript.lua loaded **")
framerate = fps:new()
print("Framerate:")
print(framerate:get())
testobj = object:new("resource/objects/iccube.obj", "iccube", vector:new(0, -5, 5))
testobj:activate()
print("Old Sphere:")
print(testobj:getApproximationSphere())
print("New Sphere:")
print(testobj:setApproximationSphere(5))
