print("** Message from LUA: Script testscript.lua loaded **")
testobj = Object:new("resource/objects/iccube.obj", "iccube", vector:new(0, -5, 5))
--testobj:activate()
print("Old Sphere:")
print(testobj:getApproximationSphere())
print("New Sphere:")
print(testobj:setApproximationSphere(5))
--testShader = Shader:new("src/shaders/basicvert.glsl", "src/shaders/basicfrag.glsl")
--testShader:activate()
print("** Message from LUA: Script ended **")

